title: WebsiteTest
author: "yeahBOYYYYY"
description: >
  This repository captures the human knowledge of the topic "Complexity Theory" in a shorthand way.


baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://yeahboyyyyy.github.io/WebsiteTest" # the base hostname & protocol for your site, e.g. http://example.com
github_username: yeahBOYYYYY # the name of your GitHub account, e.g. github_username:  jekyllrb
github_repository: WebsiteTest # the name of your GitHub repository, e.g. github_repository:  jekyllrb.github.io

# Build settings
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-navigation-tree

header_pages:
  - about.md

kramdown:
  math_engine: katex

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - conversion
